# This is a basic workflow to help you get started with Actions

name: Deploy Website


on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

- name: Deploy
  uses: peaceiris/actions-gh-pages@v3.8.0
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./


